### ISSUE TITLE
Deactivate duplicated payment methods on plugin deactivation

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-payment-methods-pro#4]
Steps to replicate the issue:

Activate PM Pro add-on
Duplicate a payment method, configure it, and activate it
Now deactivate the PM Pro add-on
The Duplicated payment method is no longer displayed on the Event Espresso > Payment Methods settings page, however it's still available as a PM at checkout.

**Comment by joshfeck** [comment]
Also reported in https://events.codebasehq.com/projects/event-espresso/tickets/10741

> 
> Eg you activate PMP and activate two PayPal Express PMs.
> Then you deactivate PMP.
> The first PPE will continue to be active in SPCO and in the admin, and the 2nd one won't be visible anywhere. Great.
> But if you deactivate the first PPE, then the second will become available in SPCO, but not in the admin so you still can't deactivate it.
> 
> So this is only a bug for PMP users who deactivate it and then try to deactivate a payment method when they previous had multiple payment methods of that type active. Although for those who experience this it might be pretty annoying (they can reactivate PMP easily enough if they're self-hosted, but ES users will need to pay up again in order to fix it, or nag us to fix it for them).
> 
> The fix for this would be to basically perform a group by type BEFORE applying the conditions whereby only active PMs are selected in SPCO, in EE core. ie, use "having" instead of "where", I think
> 
> This way EE core will effectively ignore all payment methods except the first of each type.

**Comment by sethshoultes** [comment]
@Pebblo or @joshfeck is this something you can fix?
